# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Activity',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': (('create_activities_universally', 'Can create activities universally'),)},
        ),
    ]
