# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0007_auto_20180319_1652'),
        ('work', '0002_auto_20180324_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='work name')),
                ('description', models.TextField(blank=True, help_text='Brief description for work.')),
                ('work_manual_url', models.URLField(blank=True, help_text='Wiki page for work manual.')),
                ('assigned_section', models.ManyToManyField(blank=True, help_text='Section(s) to assign this work. More than one teams or sections should be assigned.', to='members.Section')),
                ('assigned_team', models.ManyToManyField(blank=True, help_text='Team(s) to assign this work. More than one teams or sections should be assigned.', to='members.Team')),
                ('default_workplace', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work.Workplace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_section', models.ManyToManyField(blank=True, help_text='Section(s) to assign this work plan.If no team or section is assigned, default of each works will be used.', to='members.Section')),
                ('assigned_team', models.ManyToManyField(blank=True, help_text='Team(s) to assign this work plan. If no team or section is assigned, default of each works will be used.', to='members.Team')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplan_completed', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Member(s) to work on this work plan.If no member is assigned, all members in assigned teams or sections will be used.', related_name='workplan_assigned', to=settings.AUTH_USER_MODEL)),
                ('workplaces', models.ManyToManyField(blank=True, help_text='Workplace(s) for this work plan.If no workplace is assigned, default of each works will be used.', to='work.Workplace')),
                ('works', models.ManyToManyField(help_text='Work(s) to execture in this work plan. Required.', to='work.Work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlanManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
