# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_work_workplan_workplanmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkPlanManager',
        ),
        migrations.AlterField(
            model_name='work',
            name='default_workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Workplace'),
        ),
    ]
