# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20180325_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Work')),
                ('workplace', models.ForeignKey(blank=True, help_text='Change this to override default workplace. Leave it blank to use default.', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Workplace')),
            ],
        ),
        migrations.AlterField(
            model_name='workplan',
            name='works',
            field=models.ManyToManyField(help_text='Work(s) to execture in this work plan. Required.', through='work.PracticalWork', to='work.Work'),
        ),
        migrations.AddField(
            model_name='practicalwork',
            name='workplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.WorkPlan'),
        ),
    ]
