# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
