# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import recover.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=recover.models.generate_code, max_length=30, unique=True)),
                ('valid_until', models.DateTimeField(default=recover.models.generate_24h_after)),
            ],
        ),
    ]
