# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovertoken',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
