# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ja_first_name',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Last name(ja)'),
        ),
        migrations.AddField(
            model_name='member',
            name='ja_last_name',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='First name(ja)'),
        ),
    ]
