# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180313_1908'),
        ('members', '0005_auto_20180313_1906'),
    ]

    operations = [
    ]
